# Site settings
title: Matthew McCormick
email: matthew-mccormick2021.github.io
url: https://matthew-mccormck2021.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Aerospace & Mechanical Engineering Student at The University of Texas, Arlington"
meta_author: McCormick Matthew

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: matthew-mccormick2021

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: d3cec3 #80B3FF
  primary-rgb: "211,206,195" #"128,179,255"
  secondary: 323b4c #FD6E8A
  secondary-dark: 1e232d #A2122F

# Footer settings
footer:
  copyright: Matthew McCormick
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: email
    url: http://mail.google.com/matthew.mccormick2021
  - title: instagram
    url: http://instagram.com/_matt.mccormick_
  - title: Linkdin
    url: http://linkedin.com/in/matthew-mccormick-477895267

# Postal address (add as many lines as necessary)
address:
  - line: 930 Benge Drive
  - line: 429 D
  - line: Arlington, Tx 76019

# Credits content
credits: 'Github is a free to use web site creator'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
